// Raw CSV Data - 79 Ships
// Auto-generated from provided CSV

export const SHIP_CSV_DATA = [
  // HUMAN - Basic (8 ships)
  { SPECIES: 'Human', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Defender', ID: 'DEF', 'TOTAL LINE COST': '2', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Heal 1.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing', COLOUR: 'Pastel Green', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Fighter', ID: 'FIG', 'TOTAL LINE COST': '3', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 1 damage.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage', COLOUR: 'Pastel Red', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Commander', ID: 'COM', 'TOTAL LINE COST': '4', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 1 damage for every THREE of your Fighters.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage', COLOUR: 'Pastel Orange', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Interceptor', ID: 'INT', 'TOTAL LINE COST': '4', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '2', CHARGES: '1', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Heal 5  (use 1 charge).', 'POWER 2 SUBPHASE': 'Charge Declaration', 'POWER 2': 'Deal 5 damage (use 1 charge)', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'Can hold charge.', 'STACK CAPTION': '1/1 charges - X damage or X healing (on turn it\'s used) - no caption when depleted', COLOUR: 'Pastel Purple', 'NUMBER OF GRAPHICS': '2' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Orbital', ID: 'ORB', 'TOTAL LINE COST': '6', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Line Generation', 'POWER 1': 'Generate an additional line in each future build phase.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'You can have a maximum of 6 Orbitals.\n Lines may be saved.', 'STACK CAPTION': '+X lines', COLOUR: 'Pastel Blue', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Carrier', ID: 'CAR', 'TOTAL LINE COST': '6', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '2', CHARGES: '6', 'POWER 1 SUBPHASE': 'Ships That Build', 'POWER 1': 'Make a Defender  (use 1 charge).', 'POWER 2 SUBPHASE': 'Ships That Build', 'POWER 2': 'Make a Fighter (use 2 charges)', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'Can only use one power once per subphase. System: notated with CAR(X) where X is remaining charges', 'STACK CAPTION': 'X/6 charges - no caption when depleted', COLOUR: 'Pastel Yellow', 'NUMBER OF GRAPHICS': '7' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Starship', ID: 'STA', 'TOTAL LINE COST': '8', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 8 damage, once only on the turn it is built.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage (only on turn it\'s built, then no caption)', COLOUR: 'Pastel Pink', 'NUMBER OF GRAPHICS': '1' },
  
  // HUMAN - Upgraded (8 ships)
  { SPECIES: 'Human', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Frigate', ID: 'FRI', 'TOTAL LINE COST': '8', 'JOINING LINE COST': '3', 'COMPONENT SHIPS': 'DEF, FIG', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Drawing', 'POWER 1': 'Choose a trigger number for this ship, 1-6.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'If dice roll matches the trigger number, deal 6 damage. Including the turn this is built.', 'POWER 3 SUBPHASE': 'Automatic', 'POWER 3': 'Heal 2', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing - HITS X damage', COLOUR: 'Yellow', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Tactical Cruiser', ID: 'TAC', 'TOTAL LINE COST': '10', 'JOINING LINE COST': '3', 'COMPONENT SHIPS': 'DEF, DEF, FIG', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 1 damage for each TYPE of ship you have.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'Includes Tactical Cruiser as a type. TYPE are counted during End of Turn Resolution.', 'STACK CAPTION': 'X damage - ', COLOUR: 'Orange', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Guardian', ID: 'GUA', 'TOTAL LINE COST': '12', 'JOINING LINE COST': '4', 'COMPONENT SHIPS': 'DEF, DEF, COM', 'NUMBER OF POWERS': '1', CHARGES: '2', 'POWER 1 SUBPHASE': 'First Strike', 'POWER 1': 'Destroy a basic enemy ship (use 1 charge).', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X/2 charges - no caption when depleted', COLOUR: 'Blue', 'NUMBER OF GRAPHICS': '3' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Science Vessel', ID: 'SCI', 'TOTAL LINE COST': '17', 'JOINING LINE COST': '4', 'COMPONENT SHIPS': 'DEF, FIG, STA', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'If you have 1 Science Vessel: Double your Automatic healing.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'If you have 2 Science Vessels: Double your Automatic damage.', 'POWER 3 SUBPHASE': 'Line Generation', 'POWER 3': 'If you have 3 Science Vessels: Generate additional lines equal to the dice roll.', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing, X damage, +X lines', COLOUR: 'Pink', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Battle Cruiser', ID: 'BAT', 'TOTAL LINE COST': '20', 'JOINING LINE COST': '6', 'COMPONENT SHIPS': 'DEF, FIG, FIG, ORB', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Line Generation', 'POWER 1': 'Generate 2 additional lines in each future build phase.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Heal 3.', 'POWER 3 SUBPHASE': 'Automatic', 'POWER 3': 'Deal 2 damage.', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing, X damage, +X lines', COLOUR: 'Cyan', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Earth Ship', ID: 'EAR', 'TOTAL LINE COST': '23', 'JOINING LINE COST': '7', 'COMPONENT SHIPS': 'DEF, DEF, ORB, CAR(0)', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 3 damage for each of your Carriers.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage', COLOUR: 'Green', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Dreadnought', ID: 'DRE', 'TOTAL LINE COST': '27', 'JOINING LINE COST': '10', 'COMPONENT SHIPS': 'DEF, DEF, FIG, FIG, FIG, COM', 'NUMBER OF POWERS': '2', CHARGES: '', 'POWER 1 SUBPHASE': 'Drawing', 'POWER 1': 'When you complete a ship, you may make a FREE additional Fighter.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Deal 10 damage.', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'The Dreadnought\'s build power activates whenever you make a basic ship (including from Carriers) or complete an upgraded ship. It can occur multiple times per turn. Is not activated by itself or other Dreadnoughts.', 'STACK CAPTION': 'X damage', COLOUR: 'Red', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Human', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Leviathan', ID: 'LEV', 'TOTAL LINE COST': '44', 'JOINING LINE COST': '12', 'COMPONENT SHIPS': 'DEF, DEF, CAR(0), CAR(0), STA, STA', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Dice Manipulation', 'POWER 1': 'All dice rolls read as 6 for you.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Deal 12 damage.', 'POWER 3 SUBPHASE': 'Automatic', 'POWER 3': 'Heal 12.', 'EXTRA RULES': 'Carrier charges must all be used before upgrading. Overrides reroll powers.', 'STACK CAPTION': 'X healing, X damage', COLOUR: 'Purple', 'NUMBER OF GRAPHICS': '1' },
  
  // XENITE - Basic (9 ships)
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Xenite', ID: 'XEN', 'TOTAL LINE COST': '2', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '0', CHARGES: '', 'POWER 1 SUBPHASE': '', 'POWER 1': 'No power.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'No caption', COLOUR: 'White', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Antlion', ID: 'ANT', 'TOTAL LINE COST': '3', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '2', CHARGES: '1', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Heal 3  (use 1 charge).', 'POWER 2 SUBPHASE': 'Charge Declaration', 'POWER 2': 'Deal 3 damage (use 1 charge).', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'Can hold charge.', 'STACK CAPTION': '1/1 charges - X damage or X healing (on turn it\'s used) - no caption when depleted', COLOUR: 'Pastel Orange', 'NUMBER OF GRAPHICS': '2' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Mantis', ID: 'MAN', 'TOTAL LINE COST': '4', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Heal 1 for every TWO of your Xenites.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'Each Mantis can heal a maximum of 10 per turn.', 'STACK CAPTION': 'X healing', COLOUR: 'Pastel Green', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Evolver', ID: 'EVO', 'TOTAL LINE COST': '4', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Drawing', 'POWER 1': 'When built and in each future build phase, may turn one Xenite into an Oxite or an Asterite.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'If no Xenites available power cannot be used.', 'STACK CAPTION': 'No caption', COLOUR: 'Pastel Purple', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Basic - Evolved', 'SHIP NAME': 'Oxite', ID: 'OXI', 'TOTAL LINE COST': '2', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Heal 1.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing', COLOUR: 'White', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Basic - Evolved', 'SHIP NAME': 'Asterite', ID: 'AST', 'TOTAL LINE COST': '2', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 1 damage.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage', COLOUR: 'White', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Hell Hornet', ID: 'HEL', 'TOTAL LINE COST': '6', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '2', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 3 damage, once only on the turn it is built.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Deal 1 damage for every TWO of your Xenites.', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage (include upon completion damage on turn it\'s built)', COLOUR: 'Pastel Red', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Bug Breeder', ID: 'BUG', 'TOTAL LINE COST': '6', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '4', 'POWER 1 SUBPHASE': 'Ships That Build', 'POWER 1': 'Make a Xenite (use 1 charge).', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X/4 charges - no caption when depleted', COLOUR: 'Pastel Blue', 'NUMBER OF GRAPHICS': '5' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Zenith', ID: 'ZEN', 'TOTAL LINE COST': '9', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Drawing', 'POWER 1': 'When built, make an Antlion.', 'POWER 2 SUBPHASE': 'Ships That Build', 'POWER 2': 'Each future build phase: If dice roll is a 2, make a Xenite. If dice roll is a 3, make an Antlion. If dice roll is a 4, make two Xenites.', 'POWER 3 SUBPHASE': 'Upon Destruction', 'POWER 3': 'Upon destruction, make two Xenites.', 'EXTRA RULES': '', 'STACK CAPTION': 'Caption only when dice roll triggers a ship: Made X Xenite(s), Made X Antlion(s)', COLOUR: 'Pastel Yellow', 'NUMBER OF GRAPHICS': '1' },
  
  // XENITE - Upgraded (7 ships)
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Defense Swarm', ID: 'DSW', 'TOTAL LINE COST': '9', 'JOINING LINE COST': '3', 'COMPONENT SHIPS': 'XEN, XEN, XEN', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Heal 3 OR At the start of this turn, if your health is lower than your opponent\'s health: Heal 7.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing (Number of ships in stack x 3 OR 7)', COLOUR: 'Green', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Antlion Array', ID: 'AAR', 'TOTAL LINE COST': '12', 'JOINING LINE COST': '3', 'COMPONENT SHIPS': 'ANT(0), ANT(0), ANT(0)', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 3 damage OR At the start of this turn, if your health is lower than your opponent\'s health: Deal 7 damage.\n', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage (Number of ships in stack x 3 OR 7)', COLOUR: 'Orange', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Oxite Face', ID: 'OXF', 'TOTAL LINE COST': '12', 'JOINING LINE COST': '4', 'COMPONENT SHIPS': 'OXI, OXI, EVO', 'NUMBER OF POWERS': '2', CHARGES: '', 'POWER 1 SUBPHASE': 'Line Generation', 'POWER 1': 'Generate an additional line in each future build phase.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Heal 1 for each TYPE of ship your opponent has.', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'TYPE are counted during End of Turn Resolution.', 'STACK CAPTION': '+X lines, X healing', COLOUR: 'Yellow', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Asterite Face', ID: 'ASF', 'TOTAL LINE COST': '12', 'JOINING LINE COST': '4', 'COMPONENT SHIPS': 'AST, AST, EVO', 'NUMBER OF POWERS': '2', CHARGES: '', 'POWER 1 SUBPHASE': 'Line Generation', 'POWER 1': 'Generate an additional line in each future build phase.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Deal 1 damage for each TYPE of ship your \nopponent has.', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'TYPE are counted during End of Turn Resolution.', 'STACK CAPTION': '+X lines, X damage', COLOUR: 'Blue', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Sacrificial Pool', ID: 'SAC', 'TOTAL LINE COST': '12', 'JOINING LINE COST': '4', 'COMPONENT SHIPS': 'XEN, ANT(0), ANT(0)', 'NUMBER OF POWERS': '2', CHARGES: '', 'POWER 1 SUBPHASE': 'Ships That Build', 'POWER 1': 'Each future build phase, may destroy one basic ship of yours and make a Xenite for every 3 lines in that ship (round down).', 'POWER 2 SUBPHASE': '(Passive)', 'POWER 2': 'Your ships cannot be destroyed by opponent powers.', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'No caption', COLOUR: 'Red', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Queen', ID: 'QUE', 'TOTAL LINE COST': '20', 'JOINING LINE COST': '6', 'COMPONENT SHIPS': 'XEN, ANT(0), ANT(0), BUG(0)', 'NUMBER OF POWERS': '2', CHARGES: '', 'POWER 1 SUBPHASE': 'Ships That Build', 'POWER 1': 'Each future build phase, make a Xenite.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Deal 3 damage for each ship you made this turn (not including the Xenite from this Queen).', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'Damage count includes: drawn ships, upgraded ships, and ships made from other Queens, Bug Breeders, Zeniths, Sacrificial Pools.', 'STACK CAPTION': 'X damage', COLOUR: 'Cyan', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Chronoswarm', ID: 'CHR', 'TOTAL LINE COST': '25', 'JOINING LINE COST': '4', 'COMPONENT SHIPS': 'XEN, XEN, XEN, XEN, XEN, XEN, ZEN', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'End of Build Phase', 'POWER 1': 'Each turn, before the battle phase, you take an extra build phase. (Includes Dice Roll, Ships That Build and Drawing, but not Face lines.)', 'POWER 2 SUBPHASE': '', 'POWER 2': 'If you have 2: Roll 2 dice in the extra build phase.', 'POWER 3 SUBPHASE': '', 'POWER 3': 'If you have 3: Roll 3 dice in the extra build phase.', 'EXTRA RULES': 'Does not occur the turn it is built. Opponent sees the dice roll(s). If multiple players have Chronoswarms, they all use the same dice rolls. (For 2 and 3) Use only the last rolled dice for Zeniths - not each dice.', 'STACK CAPTION': 'No caption', COLOUR: 'Pink', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Xenite', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Hive', ID: 'HVE', 'TOTAL LINE COST': '35', 'JOINING LINE COST': '4', 'COMPONENT SHIPS': 'XEN, ANT(0), MAN, MAN, HEL, BUG(0), BUG(0)', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 1 damage for each of your ships.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Heal 1 for each of your ships.', 'POWER 3 SUBPHASE': '(Passive)', 'POWER 3': 'Xenites, Oxites and Asterites within your upgraded ships DO count for your other ship powers.', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing, X damage', COLOUR: 'Purple', 'NUMBER OF GRAPHICS': '1' },
  
  // CENTAUR - Basic (7 ships)
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Ship of Fear', ID: 'FEA', 'TOTAL LINE COST': '2', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Heal 4, once only on the turn it is built.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing (only on turn it\'s built, then no caption)', COLOUR: 'Pastel Green', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Ship of Anger', ID: 'ANG', 'TOTAL LINE COST': '3', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 4 damage, once only on the turn it is built.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage (only on turn it\'s built, then no caption)', COLOUR: 'Pastel Red', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Ship of Equality', ID: 'EQU', 'TOTAL LINE COST': '4', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '2', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Destroy one basic ship of yours, and one basic ship of your opponents with an EQUAL number of total lines \n(use 1 charge). ', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'Mark as each charge is used. Cannot target other Ships of Equality. If there are not two valid targets, cannot be used. If either target is destroyed, charge is still used.', 'STACK CAPTION': 'X/2 charges - no caption when depleted', COLOUR: 'Pastel Orange', 'NUMBER OF GRAPHICS': '3' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Ship of Wisdom', ID: 'WIS', 'TOTAL LINE COST': '4', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '2', CHARGES: '2', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Deal 3 damage (use 1 charge).', 'POWER 2 SUBPHASE': 'Charge Declaration', 'POWER 2': 'Heal 4 (use 1 charge).', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X/2 charges - X damage or X healing (on turn it\'s used) - no caption when depleted', COLOUR: 'Pastel Purple', 'NUMBER OF GRAPHICS': '3' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Ship of Vigor', ID: 'VIG', 'TOTAL LINE COST': '6', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Line Generation', 'POWER 1': 'Each future build phase, if dice roll is even (2, 4, 6) generate TWO additional lines.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'You can have a maximum of 3 Ships of Vigor.', 'STACK CAPTION': '+X lines on even dice, no caption on odd dice', COLOUR: 'Pastel Blue', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Ship of Family', ID: 'FAM', 'TOTAL LINE COST': '6', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '2', CHARGES: '3', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Deal 1 damage for each TYPE of ship you have\n(use 1 charge).', 'POWER 2 SUBPHASE': 'Charge Declaration', 'POWER 2': 'Heal 1 for each TYPE of ship you have (use 1 charge).', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'TYPE are counted during Charge Declaration.', 'STACK CAPTION': 'X/3 charges - X damage or X healing (on turn it\'s used) - no caption when depleted', COLOUR: 'Pastel Pink', 'NUMBER OF GRAPHICS': '4' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Ship of Legacy', ID: 'LEG', 'TOTAL LINE COST': '8', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Drawing', 'POWER 1': 'When built, generate 4 joining lines.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Deal 1 damage.', 'POWER 3 SUBPHASE': 'Automatic', 'POWER 3': 'Heal 2.', 'EXTRA RULES': 'Joining lines can be drawn immediately or saved. These may only be used as joining lines. If they complete an upgraded ship it is active this turn.', 'STACK CAPTION': 'X healing, X damage', COLOUR: 'Pastel Yellow', 'NUMBER OF GRAPHICS': '1' },
  
  // CENTAUR - Upgraded (9 ships)
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Ark of Terror', ID: 'TER', 'TOTAL LINE COST': '7', 'JOINING LINE COST': '3', 'COMPONENT SHIPS': 'FEA, FEA', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Heal equal to the dice roll this turn.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing', COLOUR: 'Green', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Ark of Fury', ID: 'FUR', 'TOTAL LINE COST': '10', 'JOINING LINE COST': '4', 'COMPONENT SHIPS': 'ANG, ANG', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal damage equal to the dice roll this turn.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage', COLOUR: 'Orange', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Ark of Knowledge', ID: 'KNO', 'TOTAL LINE COST': '12', 'JOINING LINE COST': '2', 'COMPONENT SHIPS': 'WIS(0), FAM(0)', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Dice Manipulation', 'POWER 1': 'If you have 1\n Ark of Knowledge: You may reroll the dice during build phase (for all players, the original roll \nis not used). If you have 2 Arks of Knowledge: You may reroll the dice TWICE during build phase (for all players, the original roll is not used).\n', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Heal 2.', 'POWER 3 SUBPHASE': 'Automatic', 'POWER 3': 'If you have 3\n Arks of Knowledge: Also your damage and healing are equal to whichever is higher this turn. Includes \'once only\' and charges.', 'EXTRA RULES': '', 'STACK CAPTION': 'X healing, X damage', COLOUR: 'Pink', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Ark of Entropy', ID: 'ENT', 'TOTAL LINE COST': '12', 'JOINING LINE COST': '4', 'COMPONENT SHIPS': 'EQU(0), EQU(0)', 'NUMBER OF POWERS': '2', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 7 damage.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Take 4 damage.', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage, take X', COLOUR: 'Blue', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Ark of Redemption', ID: 'RED', 'TOTAL LINE COST': '15', 'JOINING LINE COST': '3', 'COMPONENT SHIPS': 'WIS(0), WIS(0), WIS(0)', 'NUMBER OF POWERS': '2', CHARGES: '', 'POWER 1 SUBPHASE': 'Line Generation', 'POWER 1': 'Generate 2 joining lines each future build phase.', 'POWER 2 SUBPHASE': 'End of Build Phase', 'POWER 2': 'When built set your health to maximum. This is not \'healing\', and occurs before the Battle Phase. Does not affect Ark of Knowledge.', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': '+X joining lines, X health', COLOUR: 'Yellow', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Ark of Power', ID: 'POW', 'TOTAL LINE COST': '20', 'JOINING LINE COST': '6', 'COMPONENT SHIPS': 'FEA, ANG, ANG, VIG', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Line Generation', 'POWER 1': 'Each future build phase, if dice roll is even (2, 4, 6) generate FOUR additional lines.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'Deal 2 damage.', 'POWER 3 SUBPHASE': 'Automatic', 'POWER 3': 'Heal 3.', 'EXTRA RULES': 'You can have a maximum of 2 Arks of Power.\n', 'STACK CAPTION': 'X healing, X damage, +X lines', COLOUR: 'Cyan', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Ark of Destruction', ID: 'DES', 'TOTAL LINE COST': '31', 'JOINING LINE COST': '12', 'COMPONENT SHIPS': 'FEA, FEA, ANG, EQU(0), LEG', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'Deal 3 damage for each of your other ships. Does NOT include itself.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'X damage', COLOUR: 'Red', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Centaur', 'SHIP TYPE': 'Upgraded', 'SHIP NAME': 'Ark of Domination', ID: 'DOM', 'TOTAL LINE COST': '40', 'JOINING LINE COST': '12', 'COMPONENT SHIPS': 'FEA, VIG, FAM(0), FAM(0), LEG', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Line Generation', 'POWER 1': 'Generate 2 joining lines each future build phase.', 'POWER 2 SUBPHASE': 'First Strike', 'POWER 2': 'Once, on the turn it is built, at the start of the battle phase, take permanent control of TWO basic (non-upgraded) enemy ships.', 'POWER 3 SUBPHASE': 'Automatic', 'POWER 3': 'Heal 3 for each of your ships.', 'EXTRA RULES': 'Enemy ships will be removed from their fleet and added to your fleet. Their Charge powers and Automatic powers will be active for you.', 'STACK CAPTION': '+X joining lines, X health', COLOUR: 'Purple', 'NUMBER OF GRAPHICS': '1' },
  
  // ANCIENT - Basic (7 ships)
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Mercury Core', ID: 'MER', 'TOTAL LINE COST': '4', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Gain 1 red energy each battle phase.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'Pastel Red', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Pluto Core', ID: 'PLU', 'TOTAL LINE COST': '4', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Gain 1 green energy each battle phase.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'Pastel Green', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Quantum Mystic', ID: 'QUA', 'TOTAL LINE COST': '5', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '2', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'If dice roll is 1 or 2 Gain 1 blue energy.', 'POWER 2 SUBPHASE': 'Automatic', 'POWER 2': 'If dice roll is 1 or 2 heal 5.', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'You can have a maximum of 6 Quantum Mystics.', 'STACK CAPTION': 'N/A', COLOUR: 'Pastel Purple', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Spiral', ID: 'SPI', 'TOTAL LINE COST': '6', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '3', CHARGES: '', 'POWER 1 SUBPHASE': 'Automatic', 'POWER 1': 'If you have one:\n Heal 1 for each red and/or green energy you spent this turn.', 'POWER 2 SUBPHASE': '(passive)', 'POWER 2': 'If you have two:\n Also, increase your maximum health by 15.', 'POWER 3 SUBPHASE': 'Automatic', 'POWER 3': 'If you have three:\n Also, Deal 1 damage for each red and/or green energy you spent this turn.', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'Pastel Pink', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Uranus Core', ID: 'URA', 'TOTAL LINE COST': '7', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Gain 1 blue energy each battle phase.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'You can have a maximum of 6 Uranus Cores.', 'STACK CAPTION': 'N/A', COLOUR: 'Pastel Blue', 'NUMBER OF GRAPHICS': '1' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Solar Grid', ID: 'SOL', 'TOTAL LINE COST': '8', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '2', CHARGES: '4', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Gain 1 energy of each colour this battle phase \n(use 1 charge).', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'Pastel Yellow', 'NUMBER OF GRAPHICS': '5' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Basic', 'SHIP NAME': 'Cube', ID: 'CUB', 'TOTAL LINE COST': '9', 'JOINING LINE COST': '', 'COMPONENT SHIPS': '', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Once per turn, you may repeat a solar power that you cast (for free).', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'Pastel Orange', 'NUMBER OF GRAPHICS': '1' },
  
  // ANCIENT - Solar Powers (9 powers)
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Solar Power', 'SHIP NAME': 'Asteroid', ID: 'SAST', 'TOTAL LINE COST': 'N/A', 'JOINING LINE COST': 'N/A', 'COMPONENT SHIPS': '1 red energy', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Deal 1 damage.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'N/A', 'NUMBER OF GRAPHICS': '0' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Solar Power', 'SHIP NAME': 'Supernova', ID: 'SSUP', 'TOTAL LINE COST': 'N/A', 'JOINING LINE COST': 'N/A', 'COMPONENT SHIPS': '3 red energy', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Deal damage equal to the dice roll +4.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'N/A', 'NUMBER OF GRAPHICS': '0' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Solar Power', 'SHIP NAME': 'Life', ID: 'SLIF', 'TOTAL LINE COST': 'N/A', 'JOINING LINE COST': 'N/A', 'COMPONENT SHIPS': '1 green energy', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Heal 1.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'N/A', 'NUMBER OF GRAPHICS': '0' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Solar Power', 'SHIP NAME': 'Star Birth', ID: 'SSTA', 'TOTAL LINE COST': 'N/A', 'JOINING LINE COST': 'N/A', 'COMPONENT SHIPS': '3 green energy', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Heal equal to the dice roll +5.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'N/A', 'NUMBER OF GRAPHICS': '0' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Solar Power', 'SHIP NAME': 'Convert', ID: 'SCON', 'TOTAL LINE COST': 'N/A', 'JOINING LINE COST': 'N/A', 'COMPONENT SHIPS': '1 blue energy', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Generate an additional line next build phase.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '* Convert is the only way energy can be converted back into lines. Lines can be saved.', 'STACK CAPTION': 'N/A', COLOUR: 'N/A', 'NUMBER OF GRAPHICS': '0' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Solar Power', 'SHIP NAME': 'Simulacrum', ID: 'SSIM', 'TOTAL LINE COST': 'N/A', 'JOINING LINE COST': 'N/A', 'COMPONENT SHIPS': 'X blue energy', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Make a copy of a basic enemy ship.\nX = Number of lines in ship.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': 'Each ship may only be copied ONCE per turn. Ships with charges are copied as they are at the START of this turn. Copied ships CAN be upgraded. A Cube-cast makes an extra copy of target ship. Cannot copy Cube.', 'STACK CAPTION': 'N/A', COLOUR: 'N/A', 'NUMBER OF GRAPHICS': '0' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Solar Power', 'SHIP NAME': 'Siphon', ID: 'SSIP', 'TOTAL LINE COST': 'N/A', 'JOINING LINE COST': 'N/A', 'COMPONENT SHIPS': '2 red, 2 green energy', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Deal 1 damage for each Core you have.\nHeal 1 for each Core you have.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'N/A', 'NUMBER OF GRAPHICS': '0' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Solar Power', 'SHIP NAME': 'Vortex', ID: 'SVOR', 'TOTAL LINE COST': 'N/A', 'JOINING LINE COST': 'N/A', 'COMPONENT SHIPS': '2 red, 2 green, 1 blue energy', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Deal 2 damage for each TYPE of ship you have.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'N/A', 'NUMBER OF GRAPHICS': '0' },
  { SPECIES: 'Ancient', 'SHIP TYPE': 'Solar Power', 'SHIP NAME': 'Black Hole', ID: 'SBLA', 'TOTAL LINE COST': 'N/A', 'JOINING LINE COST': 'N/A', 'COMPONENT SHIPS': '3 red, 3 green, 3 blue energy', 'NUMBER OF POWERS': '1', CHARGES: '', 'POWER 1 SUBPHASE': 'Charge Declaration', 'POWER 1': 'Destroy TWO of the opponent\'s basic ships.\nDeal 4 damage.', 'POWER 2 SUBPHASE': '', 'POWER 2': '', 'POWER 3 SUBPHASE': '', 'POWER 3': '', 'EXTRA RULES': '', 'STACK CAPTION': 'N/A', COLOUR: 'N/A', 'NUMBER OF GRAPHICS': '0' }
];
